### ISSUE TITLE
Search box not always working

### ISSUE THREAD

**Issue by Bicet** [MarkJerde/LMBTFY#1]
How to reproduce the issue.
Open flycut menu, the search box is working.
click on desktop
Open flycut menu, the search box is NOT working.

EL Cap 10.11.2

**Comment by MarkJerde** [comment]
Hi Bicet.
LMBTFY is just a build repository (Let Me Build That For You) born out of resignation over all of the people who couldn't be bothered to download Xcode.  The actual Flycut project is over here: https://github.com/TermiT/Flycut

Thanks for the report though.
- Mark
